#!/usr/bin/env python3
"""Send detailed test alert with analysis reasoning."""

import asyncio
import httpx

BOT_TOKEN = "8898405035:AAHLhE6RXCaHm_HymaUChqfBYC5U_iVxT1s"
ADMIN_ID = "5994671522"

async def send_detailed_alert():
    """Send detailed alert with full analysis reasoning."""
    
    message = """
🚨 *STRONG BUY ALERT* 🚨

📈 *BBCA* - Bank Central Asia Tbk
💰 Price: Rp 9,500 (+2.5%)
📊 Score: 78.5/100

━━━━━━━━━━━━━━━━━━━━

🎯 *MENGAPA SAHAM INI BERPOTENSI?*

📌 *RINGKASAN:*
BBCA menunjukkan sinyal BUY kuat dengan conviction 82%. 
Terjadi kombinasi bullish dari sisi teknikal (momentum kuat), 
fundamental (valuasi menarik), dan akumulasi bandar (net buy 3 hari).

━━━━━━━━━━━━━━━━━━━━

🔍 *ANALISIS TEKNIKAL* (Score: 82.3/100)

✅ *TREND:* UPTRENDConfirmed
   • Price di atas MA20, MA50, MA200
   • Higher high & higher low terbentuk
   • Trend strength: Strong

✅ *MOMENTUM:* Bullish
   • RSI: 58.5 → Masuk zona bullish (50-70)
   • MACD: Bullish crossover (MACD line > Signal)
   • Stochastic: 65 (bullish, belum overbought)

✅ *VOLUME:* Accumulation
   • Volume hari ini: 2.3x rata-rata
   • OBV (On-Balance Volume): Rising
   • Smart money terdeteksi masuk

✅ *SUPPORT/RESISTANCE:*
   • Support kuat: 9,200 (prev resistance)
   • Resistance: 9,800 (ATH)
   • Risk/Reward favorable: 1:2.5

━━━━━━━━━━━━━━━━━━━━

📊 *ANALISIS FUNDAMENTAL* (Score: 74.2/100)

✅ *VALUASI:* Reasonable
   • PER: 12.5x vs Industry avg 15x → Undervalued
   • PBV: 2.8x vs 5yr avg 3.2x → Below average
   • PEG: 0.8 → Growth at reasonable price

✅ *PROFITABILITY:* Excellent
   • ROE: 18.5% → Efficient capital use
   • ROA: 2.1% → Good asset management
   • NIM: 5.2% → Healthy margin

✅ *FINANCIAL HEALTH:* Strong
   • DER: 0.8x → Safe leverage
   • CAR: 23% → Well capitalized
   • NPL: 0.9% → Low risk

✅ *GROWTH:* Positive
   • Revenue YoY: +12%
   • Earnings YoY: +15%
   • Loan growth: +10%

━━━━━━━━━━━━━━━━━━━━

💰 *FOREIGN FLOW / BANDAR* (Score: 65/100)

✅ *Akumulasi 3 hari berturut-turut*
   • Net buy: +Rp 450B (3 days)
   • Foreign ownership: 38% → Still room to 40%
   • Bandar score: 65 (Accumulation phase)

✅ *Unusual Activity:*
   • Block trade detected: 50M shares
   • Institutional buying increasing
   • Retail selling absorbed

━━━━━━━━━━━━━━━━━━━━

🤖 *AI ANALYSIS* (Qwen3.5-397b)

*"BBCA menunjukkan setup bullish yang konfirm dari multiple factors:
1. Breakout dari consolidation 2 minggu
2. Volume confirmation strong
3. Foreign flow positif konsisten
4. Fundamental solid dengan valuation reasonable

Catalyst potensial:
• Earnings release dalam 2 minggu (expected beat)
• Sector rotation ke financials
• BI rate cut expectation"*

━━━━━━━━━━━━━━━━━━━━

💡 *RECOMMENDATION*

📍 *Entry:* 9,400 - 9,500
   • Buy 50% di 9,400-9,450
   • Buy 50% di 9,450-9,500 (if breakout)

🎯 *Target Price:*
   • TP1: 9,800 (+3.2%) → 50% profit taking
   • TP2: 10,200 (+7.4%) → 50% remaining

🛑 *Stop Loss:* 9,100 (-4.2%)
   • Tighten to 9,300 if TP1 hit
   • Trail stop if strong momentum

⚖️ *Risk/Reward:* 1:2.5
   • Risk: -4.2%
   • Reward: +7.4%
   • Win probability: ~70%

━━━━━━━━━━━━━━━━━━━━

⚠️ *RISIKO YANG HARUS DIPANTAU:*

1. 📉 Market correction (IHSG resistance 7,400)
2. 📉 Foreign outflow sudden (monitor daily)
3. 📉 Earnings miss (check release date)
4. 📉 Sector rotation away from banks

━━━━━━━━━━━━━━━━━━━━

📝 *ACTION PLAN:*

✅ Monitor volume di 9,400-9,500 (must be >avg)
✅ Watch for breakout above 9,550 (confirmation)
✅ Set alert at 9,350 (add position if bounce)
❌ Avoid if gap down >2% tomorrow

━━━━━━━━━━━━━━━━━━━━

⚠️ *DISCLAIMER:*
Ini adalah analisis AI, bukan financial advice.
Lakukan riset mandiri sebelum trading.
Pastikan risk management yang baik (max 2-3% per trade).

━━━━━━━━━━━━━━━━━━━━

📊 *Generated by:* IDX AI Stock Scanner
🤖 *AI Model:* Qwen3.5-397b + ML Ensemble
📅 *Scan Time:* 2026-08-14 15:35:00
"""
    
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    
    payload = {
        "chat_id": ADMIN_ID,
        "text": message.strip(),
        "parse_mode": "Markdown",
        "disable_web_page_preview": True
    }
    
    print("="*80)
    print("SENDING DETAILED ALERT TO TELEGRAM...")
    print("="*80)
    
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(url, json=payload, timeout=15)
            result = response.json()
            
            if result.get('ok'):
                print("\n✅ SUCCESS! Detailed alert sent!")
                print(f"   Message ID: {result.get('result', {}).get('message_id')}")
                print(f"   Length: {len(message)} characters")
                print("\n📱 Check your Telegram for full analysis!")
            else:
                print(f"\n❌ Failed: {result}")
                if 'description' in result:
                    print(f"   Error: {result['description']}")
    except Exception as e:
        print(f"\n❌ Error: {e}")
    
    print("="*80)

if __name__ == '__main__':
    asyncio.run(send_detailed_alert())
