"""Initial migration

Revision ID: bb8cba7d6407
Revises: 
Create Date: 2026-07-06 11:16:57.274901
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8cba7d6407'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('board', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='id', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('analysis_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_stock_id'), 'analysis_history', ['stock_id'], unique=False)
    op.create_index(op.f('ix_analysis_history_user_id'), 'analysis_history', ['user_id'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_prices_stock_date', 'stock_prices', ['stock_id', 'trade_date'], unique=True)
    op.create_table('stock_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('fundamental_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('volume_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_scores_stock_date', 'stock_scores', ['stock_id', 'score_date'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('alert_price_above', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('alert_price_below', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlists_user_stock', 'watchlists', ['user_id', 'stock_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlists_user_stock', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_stock_scores_stock_date', table_name='stock_scores')
    op.drop_table('stock_scores')
    op.drop_index('ix_stock_prices_stock_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_analysis_history_user_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_stock_id'), table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
